### ISSUE TITLE
Good intent, need example

### ISSUE THREAD

**Issue by ukod** [Springham/MvvmCross.StackView#3]
Thank you for your module. The existence of example project with using of it will be highly appreciated.

**Comment by Springham** [comment]
Yeah I've meant to get round to adding a sample project for a while but never got round to it. It's on my to-do list!

**Comment by ukod** [comment]
Ok, thank you)

Can you explain one thing: 

I init view like this

private void PreparePricesStackView()
        {
            _priceStackView = new MvxStackView();
            innerView.Add(_priceStackView);

            _priceStackView.TopAnchor.ConstraintEqualTo(bodyText.BottomAnchor).Active = true;
            _priceStackView.BottomAnchor.ConstraintEqualTo(innerView.BottomAnchor).Active = true;
            _priceStackView.LeftAnchor.ConstraintEqualTo(bodyText.LeftAnchor).Active = true;
            _priceStackView.RightAnchor.ConstraintEqualTo(bodyText.RightAnchor).Active = true;

            _priceStackView.Axis = UILayoutConstraintAxis.Vertical;
            _priceStackView.Distribution = UIStackViewDistribution.EqualSpacing;
            _priceStackView.Alignment = UIStackViewAlignment.Center;
            _priceStackView.Spacing = 50;

            _priceStackView.TranslatesAutoresizingMaskIntoConstraints = false;
}

And bind it like this
`var bindingSet = this.CreateBindingSet<DetailsCell, MealItemViewModel>();
....
bindingSet.Bind(_priceStackView).For(s => s.ItemsSource).To(vm => vm.RecipeItems);
....
bindingSet.Apply();` 

But I didn't get how I can create the reference between view models **inside** RecipeItems. I expect something like adapter here.

**Comment by Springham** [comment]
So it's designed by default to go find the view controller that is associated with your viewmodel but you can add your own implementation by overriding GetView

**Comment by Springham** [comment]
Sample has been added now.
